---
# defaults file for appmonitor
k8s_auth_verify_ssl: false
prometheus_service_account: app-monitor-prometheus
grafana_service_account: app-monitor-grafana
prometheus_clusterrole: app-monitor-prometheus
grafana_clusterrole: app-monitor-grafana
servicemonitor_label: "app-monitor: prometheus"
pushgateway_image: "prom/pushgateway"
prometheus_app_label: "app-monitoring-operator"

oauth_proxy_memory_request: 100Mi
oauth_proxy_memory_limit: 100Mi
oauth_proxy_cpu_request: 100m
oauth_proxy_cpu_limit: 200m

grafana_memory_request: 100Mi
grafana_memory_limit: 200Mi
grafana_cpu_request: 100m
grafana_cpu_limit: 200m

routes_use_encryption: true
prometheus_api_group: app-monitoring.io
registry: registry.redhat.io
openshift_version: v3.11

grafana_storage_type: none
grafana_dashboard_configmap: grafana-data
cluster_default_image_pull_policy: Always

replicas: 1