apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appmonitors.app-monitoring.io
spec:
  group: app-monitoring.io
  names:
    kind: AppMonitor
    listKind: AppMonitorList
    plural: appmonitors
    singular: appmonitor
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
