---

- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    image_name: app-monitoring.io/app-monitoring-operator:testing
    custom_resource: "{{ lookup('file', '/'.join([deploy_dir, 'crds/app-monitoring_v1_appmonitor_cr.yaml'])) | from_yaml }}"
  tasks:
  - name: Create the app-monitoring.io/v1.AppMonitor
    k8s:
      namespace: '{{ namespace }}'
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/app-monitoring_v1_appmonitor_cr.yaml'])) }}"

  - name: Get the newly created Custom Resource
    debug:
      msg: "{{ lookup('k8s', group='app-monitoring.io', api_version='v1', kind='AppMonitor', namespace=namespace, resource_name=custom_resource.metadata.name) }}"

  - name: Wait 40s for reconciliation to run
    k8s_facts:
      api_version: 'v1'
      kind: 'AppMonitor'
      namespace: '{{ namespace }}'
      name: '{{ custom_resource.metadata.name }}'
    register: reconcile_cr
    until:
    - "'Successful' in (reconcile_cr | json_query('resources[].status.conditions[].reason'))"
    delay: 4
    retries: 10

- import_playbook: '{{ playbook_dir }}/../default/asserts.yml'
